inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - lib/templates/rails/scaffold_controller/controller.rb

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false
