development: &development
  bucket: <%= ENV.fetch('S3_BUCKET') %>
  access_key_id: <%= ENV.fetch('S3_ACCESS_KEY') %>
  secret_access_key: <%= ENV.fetch('S3_SECRET_KEY') %>
  max_file_size: 10485760
  acl: private
  region: <%= ENV.fetch('S3_REGION') %>

test:
  <<: *development

staging:
  <<: *development

production:
  <<: *development
